sudo: required
language: minimal
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "tFWVPVl7fhp0EFdZZ0iOBeq0Bvka98C4DHuxM/TEubSx0423YhVPEucL0lv3lsPg7VE+XSwP0N8n6VCUEFlqJeab0WkU5dcjYdwSbE1XlCZuzh/SawYDMgVYpSGrtYZ5rXuqQpEhSrDDwAVgycokyg2IGMBdshNg4fpwdB2Y3xIzQ1kXDnmh8TRMvk54Mg9zxcRXfKNmbbpRwW2SjcmCYUhm3kWoJM6Ev4+JVtxrI4zCXw8BIEOIa41cRjtNLXgcNibU39jlzQ3+udcU2DuMf3kEuH6fesn7qG3v+dryd0LTBOV/uHu2kJVcdLyPUvD2q7EeDtqITWjShXA7pafldSeUMQyvntQbYq/1Bee2JHyq+5Ih769a6KxmJMaUCtps6iUidmtaZLZnzVXZUR9IsaKklYh5I/4+P7xzq4HkDawlgbXoOn3xs/Ij5zSRA063Mo/l0BK1dCQrGqMTHVFzvXiRcEHe9GkkLSFx7dmOdxQA6YW4k8eWCSq3UH5CrC0aMTEDeNf7i2QRQm7bnyoN83/MTH6vKM9rKl96POt1qMJsITE5447nTfzeUohI+9T+G3sR/CpW9L0k7No1zKM45wchfUSPHdeWdXMXphwEZq9EOqhTTUvJw+yHYyCUJPUxu9IVEVpTa0eAjSHN8UtHSQGtR+2F7auKxKECXLB7Xq4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "DwdElADEFPEN99x+T+7krIeqs9O1ijImhzbueTNUhaMHx/M5MGlAyM1B+kQ0s9YcaCmPQvgppP6IVv4ifHxc/NABVa4s5+9/4VdZS1rPYuHVSmJr5oWYwFtG23WyZYlCJKumtbJSamXujMJUoVHimwgxpk8bJU/j/LvXtnGrnrdZDwrQdn4QktTpM1QqHlEfFkEDxk6Dc6Pft0xWVOBlrT2JHHYe4TVuLmjNTsIVhtKjWBXofNQb8tYddRcki5D+iuQEJMkMFCQFEh16qXddRL/CgnwH3zm7xLWf6guZzcc1V1mvrg0BMYTFIm8nDx83fk3u9CzcvzT8XVS6ZxpXvcPdz6i1NkxKIPpcsORRlW7ihcOUVPJZPBhJQWfoXdFGJxmiCZ9w1YSqbe8grhlpUBB4G5y/71BZEIy3eiA7m7+F4KVlIv6pkCr2ilNywxEEdanyWkAw4pX4A9eyPa1c/dLjL8JDk4yvTZvwyrJqBKbEj6qbg9zHlj+4AoDruX9D7qgKXk8Zb6lZNhIPS+dAzTVc/ZMq4iiOjp+tOnm/xgU9PihksqWU9lFfKJmhGzjGA0SPTPlwg1I2vhalvwBfM7g3E111QaQwklDtx0UDxMHpIvRbSQtA5EE0RmGvXFynXfMQYGkUKtQj0z+LqEjvtv+t/ObPD2BQ7o/5pIV2g30="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="baseimage-war"

script:
  - export DOCKER_TARGET="${ECR_REPO}/${ARTIFACT_NAME}:ci-${TRAVIS_BUILD_NUMBER}"
  - docker build -t ${DOCKER_TARGET} .
  - docker images

deploy:
  provider: script
  script: >-
    ./ci-tools/build/upload-image.sh $ARTIFACT_NAME &&
    export BRANCH_TAG="${ECR_REPO}/${ARTIFACT_NAME}:${TRAVIS_BRANCH}" &&
    echo $BRANCH_TAG &&
    docker tag $DOCKER_TARGET $BRANCH_TAG &&
    docker push $BRANCH_TAG
  on:
    all_branches: true
