sudo: required
dist: bionic
language: minimal
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "tFWVPVl7fhp0EFdZZ0iOBeq0Bvka98C4DHuxM/TEubSx0423YhVPEucL0lv3lsPg7VE+XSwP0N8n6VCUEFlqJeab0WkU5dcjYdwSbE1XlCZuzh/SawYDMgVYpSGrtYZ5rXuqQpEhSrDDwAVgycokyg2IGMBdshNg4fpwdB2Y3xIzQ1kXDnmh8TRMvk54Mg9zxcRXfKNmbbpRwW2SjcmCYUhm3kWoJM6Ev4+JVtxrI4zCXw8BIEOIa41cRjtNLXgcNibU39jlzQ3+udcU2DuMf3kEuH6fesn7qG3v+dryd0LTBOV/uHu2kJVcdLyPUvD2q7EeDtqITWjShXA7pafldSeUMQyvntQbYq/1Bee2JHyq+5Ih769a6KxmJMaUCtps6iUidmtaZLZnzVXZUR9IsaKklYh5I/4+P7xzq4HkDawlgbXoOn3xs/Ij5zSRA063Mo/l0BK1dCQrGqMTHVFzvXiRcEHe9GkkLSFx7dmOdxQA6YW4k8eWCSq3UH5CrC0aMTEDeNf7i2QRQm7bnyoN83/MTH6vKM9rKl96POt1qMJsITE5447nTfzeUohI+9T+G3sR/CpW9L0k7No1zKM45wchfUSPHdeWdXMXphwEZq9EOqhTTUvJw+yHYyCUJPUxu9IVEVpTa0eAjSHN8UtHSQGtR+2F7auKxKECXLB7Xq4="
    # AWS_SECRET_ACCESS_KEY
    - secure: "DwdElADEFPEN99x+T+7krIeqs9O1ijImhzbueTNUhaMHx/M5MGlAyM1B+kQ0s9YcaCmPQvgppP6IVv4ifHxc/NABVa4s5+9/4VdZS1rPYuHVSmJr5oWYwFtG23WyZYlCJKumtbJSamXujMJUoVHimwgxpk8bJU/j/LvXtnGrnrdZDwrQdn4QktTpM1QqHlEfFkEDxk6Dc6Pft0xWVOBlrT2JHHYe4TVuLmjNTsIVhtKjWBXofNQb8tYddRcki5D+iuQEJMkMFCQFEh16qXddRL/CgnwH3zm7xLWf6guZzcc1V1mvrg0BMYTFIm8nDx83fk3u9CzcvzT8XVS6ZxpXvcPdz6i1NkxKIPpcsORRlW7ihcOUVPJZPBhJQWfoXdFGJxmiCZ9w1YSqbe8grhlpUBB4G5y/71BZEIy3eiA7m7+F4KVlIv6pkCr2ilNywxEEdanyWkAw4pX4A9eyPa1c/dLjL8JDk4yvTZvwyrJqBKbEj6qbg9zHlj+4AoDruX9D7qgKXk8Zb6lZNhIPS+dAzTVc/ZMq4iiOjp+tOnm/xgU9PihksqWU9lFfKJmhGzjGA0SPTPlwg1I2vhalvwBfM7g3E111QaQwklDtx0UDxMHpIvRbSQtA5EE0RmGvXFynXfMQYGkUKtQj0z+LqEjvtv+t/ObPD2BQ7o/5pIV2g30="
    # FLOW_TOKEN
    - secure: "jcd/dvyEu9wllho5wAHGaBzO1tZygidc6g+JclRDQ61QeFSIybw/HeFME7sHMthlG24pHojBn4tC9K4WLiYAqKkrR668qe3rpCK+9q9mjFvTe70BDAbc0sWaP7gr5YudIcFPgWn1KXow59oIUQMmmFuN9rvEUUkgV04ADpZD5UMREEm37at8Xyf7v+OmwmdydYH23XJ0gjrdVe/I2vmIlJejjb8QWtekpr3BeCkH4zPoG1IdXNbS8WxQx7unMkpKX48UL8Z4winzgapAwfPmT24y/gFT08EWZPPiCRwmReKnKJ+JOxBN+49KNqNYQdS1VKW+rYG3ydRkNgy9h64XLtw/h1WLHTbhSCYq86UBgl4eW7SF/3Hzp6eOyD7qlR4ULhEl6kh4+oX3poOY2VFERGL117rwBT/dM8SzOE8RhTk9rIXIF8OT/E3QskyFlmiWFtBOUr9ZC0i+rvxZJ3H8qP6llh0QQbIMQJ+WqNmha+tBAXYzlvpQZw5GAvee/nwluiruo0DkiqXCxyslKU0eNTG8u/BhmVuNIG7EJiZ8alAm4FpK1oDb5C5DfAZTFy2gCsB6te/VjQuqSU9kZHJiYvc018LGUwF93z4qpSsKDt0rV2LweJ8qH+5SqfR3Si5T4fk5gqL9A7ARuMnmVciW+kVIEf73MtD7V0E/6IrWgnE="
    # GITHUB_TOKEN
    - secure: "MBGr8juNlVHMbx5JQtSerF8njOrOwBA3hsQvpjLmjfXj0uOtIboKq+1tBwa8aYxlr5jeLZOHvnDlM6w2P9yPR1QHvBFo4GTvm+OZ0CBqzZIA5kqeKt9KRRGoDpuBh6uVlxvbNccdF7OkMhsj25ZaY2SBk6PE/SEIY4fuXjJZ6ewblnIkOMkhCh+vvz+1jVdIpj7qGVbZloM/CZUWsF4/TFMVCKTlwdWkrRsPF+H7FtGn+ma8+wEI1X5io0ZKqPrZcKTBAbJBRKxbXgieV7dQMPntQ79pP1bvqnWlMcpKXco6NjJop56/8w9BvhqXGbbit9x3wFUrn+m9FhQIu7yc2lcy5OTpS18rwsmxVjxHB3OVsl/YArOdzsVEeKV4CE0RSI2HFJc1DA7qwacQ99GvTOtOx40aZg6e32htk/Loxx6v9+bQah4M/KmF2VXes8mTa/l+bum5+TzFhGMdTyU0N9mt8Fzo0nnohcIR0OBmJdbkYofV3Ouh/TrMLe+/UzwsqbRjZGiyosOXfJQlJ4IwTEEaH9ZZhQnCiBrOj/sIdR+iPeUeFiZ23eaPn1BcaeTKrnCIS4wOcvYBWrJZxMu016AyUY4M0j4AdBrEXDFSh+LFR1p9xZA/fqj76WiJ+gkBYD7hBx86U7XauN9CxqbWLuQ+Kj3reqMRKeUyh+fQjQI="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="baseimage-war"

script:
  - export DOCKER_TARGET="${ECR_REPO}/${ARTIFACT_NAME}:ci-${TRAVIS_BUILD_NUMBER}"
  - docker build -t ${DOCKER_TARGET} .
  - bash ci-tools/version_check/version_check.sh
  - docker images

deploy:
  provider: script
  script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME $TRAVIS_BRANCH
  on:
    all_branches: true
